corpus = "./static/language_data/shai.json"
layouts = [ "./static/layouts/english" ]        #these can include glob patterns
corpus_configs = "./static/corpus_configs/**"   #these can include glob patterns
trigram_precision = 1000
max_cores = 32

[weights]
sfbs = -7.0
sfs = -1.0
lateral_penalty = 1.0
stretches = -0.3
pinky_ring_bigrams = -0.2
inrolls = 2.5
outrolls = 2.4
onehands = 0.9
alternates = 0.4
alternates_sfs = 0.1
redirects = -3.4
redirects_sfs = -4.2
bad_redirects = -4.9
bad_redirects_sfs = -5.5

[weights.finger_weights]
lp = 1.4
lr = 3.6
lm = 4.8
li = 5.5
lt = 3.3
rt = 3.3
ri = 5.5
rm = 4.8
rr = 3.6
rp = 1.4

[weights.max_finger_use]
penalty = 0
pinky = 9.0
ring = 14.0
middle = 20.0
index = 20.0
thumb = 22.0
