[package]
name = "oxeylyzer-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
oxeylyzer-core = { path = "../oxeylyzer-core" }
oxeylyzer-repl = { path = "../oxeylyzer-repl" }
oxeylyzer-resources = { path = "../oxeylyzer-resources" }
anyhow = { workspace = true }
ratatui = "0.29"
crossterm = "0.28"
xflags = { git = "https://github.com/O-X-E-Y/xflags/" }
