name: Release Tauri

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            args: ""
          - os: windows-latest
            args: ""
          - os: macos-latest
            args: "--target aarch64-apple-darwin"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin  # needed for macOS cross

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Linux deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install JS deps
        run: bun install
        working-directory: oxeylyzer-tauri

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: oxeylyzer-tauri
          tagName: ${{ github.ref_name }}
          releaseName: Oxeylyzer ${{ github.ref_name }}
          args: ${{ matrix.args }}
          draft: true
